### ISSUE TITLE
ray_cone_angle typo in sort kernel

### ISSUE THREAD

**Issue by MilchRatchet** [jan-van-bergen/GPU-Raytracer#36]
I think the assignment should go to ray_cone_width in line 233.

https://github.com/jan-van-bergen/GPU-Raytracer/blob/edf3be41755b87c06d92640a9587a9f6d49e6807/Src/CUDA/Pathtracer.cu#L229-L234

**Comment by jan-van-bergen** [comment]
Yep you are absolutely right, thank you very much!
