### ISSUE TITLE
Does it render in real-time?

### ISSUE THREAD

**Issue by lonnietc** [jan-van-bergen/GPU-Raytracer#37]
Hello,

I am interested in real-time raytracing for a project that I am working on now and was wondering if your code renders in realtime?

Thanks

**Comment by Pjbomb2** [comment]
Unfortunately, the creator of this project, Zuen, has passed away
It does render in real time though, but only to an extent

**Comment by lonnietc** [comment]
I am so very sorry to hear of the passing of Zuen.  I am interested in seeing if it is possible to truly develop (or at least modify in this case) a 3D engine game called Tesseract to support real-time ray tracing as well as a few other ideas. 

Maybe, I will be able to incorporate some of Zuen's work into the project to honor him and his contributions to the science.

Best Regards and have a great day
